### ISSUE TITLE
下拉刷新上拉加载是一项功能

### ISSUE THREAD

**Issue by geeklx** [HarmonyCandies/loading_more_list#5]
大佬你看看这个库
https://gitee.com/zhongrui_developer/PullToRefresh
要不是，你这个库优点是底部没bug，其他的都不如这个库，这个库没解决底部bug，不然就火了，希望大佬多参考一下市面的需求

**Comment by zmtzawqlp** [comment]
别人是别人，为啥我一定要跟别人的一样。。。做开源不是为了火不火

**Comment by geeklx** [comment]
你是个人才
